linters:
  disable-all: false
  enable:
    # defaults
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # stuff I'm adding
    - exhaustive
    #    - gochecknoglobals
    #    - gochecknoinits
    - gofmt
    - nonamedreturns
    - predeclared
  fast: false
run:
  skip-dirs:
    - test-inputs
    - contexts
issues:
  exclude:
    - 'SA1019: cli.CreateProcessorLegacy'