// Code generated by logcopter-gen; DO NOT EDIT.

package patternmatcher

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.oak.pkg.patternmatcher")
