// Code generated by logcopter-gen; DO NOT EDIT.

package dump

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.oak.pkg.tree-sitter.dump")
