// Code generated by logcopter-gen; DO NOT EDIT.

package tree_sitter

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.oak.pkg.tree-sitter")
